### ISSUE TITLE
Model path problem

### ISSUE THREAD

**Issue by rettinghaus** [qurator-spk/sbb_binarization#42]
Why is it is not looking in the given `--model-dir` for the model but rather in it's `model` subdirectory?

**Comment by mikegerber** [comment]
It is looking for `*.h5` files in `--model-dir`. Perhaps you need to give more information, like the exact command you tried to execute and an `ls` of the `--model-dir`?

**Comment by rettinghaus** [comment]
When I do `-m model` I get 

> `OSError: SavedModel file does not exist at: model/model/model_bin_sbb_ens.h5/{saved_model.pbtxt|saved_model.pb}`

With `-m ./model`

> `OSError: SavedModel file does not exist at: ./model/./model/model_bin_sbb_ens.h5/{saved_model.pbtxt|saved_model.pb}`

That's because you do a `glob` with the given path on init, and then join the file path with `model_dir` in `load_model`. This cannot work.

**Comment by mikegerber** [comment]
Interesting is why I could not reproduce this problem at first:

```
>>> import os.path
>>> os.path.join("/home/mike/devel/qurator-data/sbb_binarization/2022-08-16/", "/home/mike/devel/qurator-data/sbb_binarization/2022-08-16/model_bin_hybrid_trans_cnn_sbb_ens.h5")
'/home/mike/devel/qurator-data/sbb_binarization/2022-08-16/model_bin_hybrid_trans_cnn_sbb_ens.h5'
```

@kba 👀

**Comment by rettinghaus** [comment]
Yes, it's only working for absolute paths, not relative ones. Maybe better to use proper path objects here instead of `os.path`?

**Comment by bertsky** [comment]
Looks like this is fixed, right?

**Comment by rettinghaus** [comment]
It is.

**Comment by vahidrezanezhad** [comment]
> Looks like this is fixed, right?

Sorry for late response. Yes it is already fixed.
