### ISSUE TITLE
[transformer_model_integration] "Normal" CLI does not produce useful output

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/sbb_binarization#46]
On the transformer_model_integration branch, the normal CLI does not produce useful output

- I'm using the image from https://qurator-data.de/examples/actevedef_718448162.first-page.zip
- This fails with a (transparent?) empty output TIFF: `sbb_binarize --patches --model-dir ~/devel/qurator-data/sbb_binarization/2022-08-16/ OCR-D-IMG_00000024.tif OCR-D-IMG_00000024-bin.tif`
- This - the OCR-D CLI - works(!): `ocrd-sbb-binarize -I OCR-D-IMG -O OCR-D-IMG-BIN -P model /home/mike/devel/qurator-data/sbb_binarization/2022-08-16`

**Comment by vahidrezanezhad** [comment]
> On the transformer_model_integration branch, the normal CLI does not produce useful output
> 
> * I'm using the image from https://qurator-data.de/examples/actevedef_718448162.first-page.zip
> * This fails with a (transparent?) empty output TIFF: `sbb_binarize --patches --model-dir ~/devel/qurator-data/sbb_binarization/2022-08-16/ OCR-D-IMG_00000024.tif OCR-D-IMG_00000024-bin.tif`
> * This - the OCR-D CLI - works(!): `ocrd-sbb-binarize -I OCR-D-IMG -O OCR-D-IMG-BIN -P model /home/mike/devel/qurator-data/sbb_binarization/2022-08-16`

MIke! Avoid to write output as tif file. Writing as png format would solve the issue!!

**Comment by mikegerber** [comment]
![borat you joke tumblr_m8v40yGISF1qml34n540](https://user-images.githubusercontent.com/34309482/186144914-d2ee3805-54eb-475d-9449-999ea1c710a5.gif)

**Comment by mikegerber** [comment]
Closing in favour of the real problem (#47)
