### ISSUE TITLE
Saving to TIFF does not work

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/sbb_binarization#47]
E.g.
~~~
% sbb_binarize --patches --model-dir /home/mike/devel/qurator-data/sbb_binarization/2022-08-16/ OCR-D-IMG_00000024.tif OCR-D-IMG_00000024-bin.tif
~~~
produces a transparent(?) TIFF with no content. No warning, no error.

See also #46.

**Comment by mikegerber** [comment]
I had a brief look into checking the result of `cv2.imwrite`. While this would be a good idea in any case, it reports success (`True`) for the TIFF...

**Comment by mikegerber** [comment]
To be clear: I don't need TIFF output, it would 100% be ok if it would write a good image file OR threw an error (instead of a broken TIFF).

**Comment by mikegerber** [comment]
@vahidrezanezhad suggests in a private message that downgrading could help...
> install opencv-python-3.4.15.55

**Comment by bertsky** [comment]
@mikegerber can you please try with #59 again?

**Comment by mikegerber** [comment]
> @mikegerber can you please try with #59 again?

Using 0.1.0 (includes #59) and model 2021-03-09 SavedModel (**not** 2022-08-16, but 2021-03-09 as this is the latest from the README) I seems to work.

(I had some issues with the models zips, see #63, maybe that was related.)
