### ISSUE TITLE
strange border artifacts in patch mode

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/sbb_binarization#49]
I sometimes get output which looks like this:

| input | output | 
| --- | --- |
| ![Evakuierung_von_Polen_Ansieldung_WD_Lask_0168 IMG-NORM](https://user-images.githubusercontent.com/38561704/194917298-cd19b30d-2a41-4a16-a0c2-0566ec7776b6.png) | ![Evakuierung_von_Polen_Ansieldung_WD_Lask_0168 IMG-BINSBB](https://user-images.githubusercontent.com/38561704/194917210-2050ef3e-e112-4e16-b4ad-ccea198763ca.png) |

Could this be a problem with the patch size or patching in general? Should I try to crop first?

**Comment by bertsky** [comment]
Dear @vahidrezanezhad thanks for the explanation! That makes sense. I'll change my workflow. (Maybe you wanna document some recommendations in that regard. Please close when you see fit.)

**Comment by cneud** [comment]
> Maybe you wanna document some recommendations in that regard

I will update the readme accordingly.
