### ISSUE TITLE
Numpy issue?

### ISSUE THREAD

**Issue by kba** [qurator-spk/sbb_binarization#57]
@jbarth-ubhd in https://github.com/OCR-D/ocrd_all/issues/348

> Dear reader, tried sbb-textline (recommended on step 1), got this error message:
> 
> ```
>   File "/usr/local/lib/python3.6/site-packages/sbb_binarize/sbb_binarize.py", line 270, in run
>     img_last[:, :][img_last[:, :] > 0] = 255
> TypeError: 'int' object is not subscriptable
> ```
> 
> (almost) complete workflow environment see https://digi.ub.uni-heidelberg.de/diglitData/v/duerer1527_-_aa.zip . Extracts to directory "aa". See run.sh and ocrd.log
> 
> ocrd.sif -> ocrd-2022-08-15.sif (not a newer one because [OCR-D/ocrd_tesserocr#189](https://github.com/OCR-D/ocrd_tesserocr/issues/189) )

@bertsky:

> Probably one of the recent Numpy changes.
>
> Which version of numpy and sbb_binarize is this?

@jbarth-ubhd:

> > singularity exec -e ocrd.sif ocrd-sbb-binarize -V
> Version 0.0.10, ocrd/core 2.38.0
> 
> > singularity exec -e ocrd.sif python -c "import numpy as np
> > print(np.__version__)"
> 1.19.5

**Comment by jbarth-ubhd** [comment]
PS: from [docker 2022-08-15](https://hub.docker.com/layers/ocrd/all/2022-08-15/images/sha256-2f331331c342acb403a4d32ed17644393c94a1aa602959d3cbc3b8ca465cddba?context=explore)

**Comment by jbarth-ubhd** [comment]
Oops. Wrong permissions. Now downloadable.

**Comment by jbarth-ubhd** [comment]
Tested with ocrd/all:latest → this bug is fixed. 

Now:
```
  File "/usr/local/lib/python3.8/site-packages/sbb_binarize/sbb_binarize.py", line 40, in __init__
    raise ValueError(f"No models found in {self.model_dir}")
ValueError: No models found in /home/hd/hd_hd/hd_wu120/ocrd_models/sbb-binarize/models/model_bin_sbb_ens.h5
Command exited with non-zero status 1
```
[hd_wu120@o05i15 aa]$ md5sum /home/hd/hd_hd/hd_wu120/ocrd_models/sbb-binarize/models/model_bin_sbb_ens.h5
bad4dddb8db72bd06fed67c6117e67b7  /home/hd/hd_hd/hd_wu120/ocrd_models/sbb-binarize/models/model_bin_sbb_ens.h5
```

Ok the md5sum of the model begins with "bad...", this is self-explaining

**Comment by bertsky** [comment]
Better yet: use the models attached to the latest release on the main repo. See also #59.

So everything is working for you now?

**Comment by jbarth-ubhd** [comment]
Yes, the bug `TypeError: 'int' object is not subscriptable` is gone.
