### ISSUE TITLE
Output image is not bitonal

### ISSUE THREAD

**Issue by cneud** [qurator-spk/sbb_binarization#58]
With [current master](https://github.com/qurator-spk/sbb_binarization/commit/ae45802f6186ba9ba6786441d4fa046a59bfabad), and JPEG as the input/output image file format, I get output images which look bitonal/black-and-white, but actually aren't and use 8-Bit and 256 colors. 

Perhaps this has to do with the `opencv-python-headless` version, will try downgrading according to [this comment](https://github.com/qurator-spk/sbb_binarization/issues/47#issuecomment-1223942036).

**Comment by cneud** [comment]
Attached an example output image that is not bitonal 

![30744015_1900-01-03_007 bin](https://user-images.githubusercontent.com/952378/228803719-e4ffe065-af68-45e8-9213-8c90d9968864.jpg)

**Comment by cneud** [comment]
Source image 

![30744015_1900-01-03_007](https://user-images.githubusercontent.com/952378/228806047-137d59e2-8620-4447-8178-0ed94d97ab2e.jpg)

**Comment by bertsky** [comment]
I can reproduce. The histogram contains all sorts of values in between. Only happens with JPEG output, not with PNG. 
```
  Histogram:
   2280762: (  0,  0,  0) #000000 gray(0)
    534258: (  1,  1,  1) #010101 gray(1)
    331131: (  2,  2,  2) #020202 gray(2)
    164378: (  3,  3,  3) #030303 gray(3)
     65846: (  4,  4,  4) #040404 gray(4)
     22177: (  5,  5,  5) #050505 gray(5)
      5745: (  6,  6,  6) #060606 gray(6)
      1120: (  7,  7,  7) #070707 gray(7)
       154: (  8,  8,  8) #080808 gray(8)
        18: (  9,  9,  9) #090909 gray(9)
         1: (245,245,245) #F5F5F5 gray(245)
        15: (246,246,246) #F6F6F6 gray(246)
       150: (247,247,247) #F7F7F7 gray(247)
      3338: (248,248,248) #F8F8F8 gray(248)
      8618: (249,249,249) #F9F9F9 gray(249)
     36704: (250,250,250) #FAFAFA gray(250)
     98630: (251,251,251) #FBFBFB gray(251)
    259889: (252,252,252) #FCFCFC gray(252)
    524927: (253,253,253) #FDFDFD gray(253)
    856137: (254,254,254) #FEFEFE gray(254)
  13721678: (255,255,255) #FFFFFF gray(255)
```
According to [OpenCV documentation](https://docs.opencv.org/3.4/d4/da8/group__imgcodecs.html#gabbc7ef1aa2edfaa87772f1202d67e0ce), we must ensure to use uint8 here – which we don't (numpy uses int64 with `max()==255`). 

But the fix is **not** as simple as using `.astype(np.uint8)`. By also setting ...
```python
[cv2.IMWRITE_PNG_BILEVEL, 1, 
 cv2.IMWRITE_JPEG_QUALITY, 100, 
 cv2.IMWRITE_JPEG_OPTIMIZE, 0, 
 cv2.IMWRITE_JPEG_PROGRESSIVE, 0]
```
 ... in the last parameter to imwrite, I was able to get the histogram down to:
```
  Histogram:
   3314751: (  0,  0,  0) #000000 gray(0)
     90838: (  1,  1,  1) #010101 gray(1)
    150402: (254,254,254) #FEFEFE gray(254)
  15359685: (255,255,255) #FFFFFF gray(255)
```

which _still_ is not pure binary.
